########## 开启 Spring Boot 的 Bean 重写机制
spring:
  main:
    allow-bean-definition-overriding: true
########## Eureka Clinet 连接 Eureka Server 地址
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:9999/eureka